#数据源配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.247.164:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 520wcj
      #初始化连接大小
      initialSize: 5
      #最小空闲连接数
      minIdle: 5
      #最大连接数
      maxActive: 20
      #最大等待时间，单位：毫秒
      maxWait: 10000
      #从连接池中取出连接时进行检测
      testOnBorrow: true
      #归还到连接池中前进行检测
      testOnReturn: false
      #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位
      timeBetweenEvictionRunsMillis: 60000
      #连接在池中保持空闲而不被空闲连接回收器线程，(如果有)回收的最小时间值，单位毫秒
      minEvictableIdleTimeMillis: 300000
      #数据源监控
      stat-view-servlet:
        #登录密码
        login-password: 520wcj
        #登陆用户名
        login-username: root
        #数据源访问url
        url-pattern: /druid/*
        #数据源启用
        enabled: true
  #上传文件大小配置
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 50MB
      #上传文件大小
      max-request-size: 100MB
  #配置mongodb
  data:
    mongodb:
      host: 172.16.247.164
      database: blog
#fastdfs配置
fdfs:
  #读取时间
  so-timeout: 2500
  #连接超时时间
  connect-timeout: 600
  #缩略图大小
  thumb-image:
    width: 100
    height: 100
  #tracker地址
  tracker-list:
    - 106.52.198.68:22122
upload:
  #上传的基础路径
  base-url: http://106.52.198.68/
  #允许上传文件类型
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpng
    - audio/mp3
    - audio/flac

#shiro配置
shiro:
  #加密方式
  hash-algorithm-name: md5
  #散列次数
  hash-iterations: 2
  #退出登录url
  logout-url: /logout
  #拦截路径
  authc-urls:
    - /**
  #放行路径
  anon-urls:
    - /*/login
    - /user/login
    - /user/register
    - /link/list
    - /music/listFront
    - /blog/list
    - /blog/read/**
    - /blog/recommendRead
    - /blog/getTimeLine
    - /blog/getGoods/**
    - /blog/getCollection/**
    - /blog/getTotal
    - /admin/getInfo
    - /type/listFront
    - /about/read
    - /comment/getComment/**
    - /comment/getCommentGoods/**
    - /rotation-picture/listFront











